apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: node-app:latest
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "demo"
          ports:
            - containerPort: 8787
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  type: NodePort
  ports:
    - port: 8787
      targetPort: 8787
      nodePort: 30000
  selector:
    app: node-app
