


services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - capstone_my-network

    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 3  

  app:
    build: .
    container_name: node-app
    ports:
      - "8787:8787"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: demo
    depends_on:
      - mysql
    networks:
      - capstone_my-network 

networks:
  my-network:
    driver: bridge      

volumes:
  mysql-data:
